# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f73dbff0483b1935f7bcec888647846391b730fc79a55985bc50521495b53e1a6b05b396f26cb347842d289aed5b183e66989b0ed7b56e794357ec86582099b

test:
  secret_key_base: b78488b41f7a48dd07a615721b3c7eb9c06de2de5c8743c0af73d63f3c0fdf41e25387eb84f42e343464f8c97d55d889bf865140a17374314ca43da08277ba4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
